name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.template.Magic
description: 'A magic plugin'
authors: ['Ga_Mes']
contributors: ['']
website: ${WEBSITE}

commands:
  playerdata:
    description: Сохраняет данные игрока
    usage: /<command> save
    aliases: [pdata]
    default: true
  customgive:
    description: Выдаёт кастомный предмет
    usage: /<command> id
    aliases: [cgive]
    default: op

depend: []
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'