name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.template.Magic
description: 'A magic plugin'
authors: ['Ga_Mes']
contributors: ['']
website: ${WEBSITE}

depend: []
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'